version: '3'

services:
  app:
    container_name: task-app
    build: .
    ports: 
      - 8080:8080
  
  database:
    container_name: task-app-database
    env_file:
      - .env
    image: mysql:5.7.37
    restart: always
    ports:
      - $DATABASE_LOCAL_PORT:$DATABASE_DOCKER_PORT
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_PASSWORD=$DATABASE_PASSWORD
      - MYSQL_DATABASE=$DATABASE_NAME
  
  redis:
    image: redis